import Navigation from '@/components/navigation/navigation';

export const metadata = {
    title: "Smuk Nu",
    description: "Generated by create next app",
  };

export default function siteLayout({ children }) {
	return (
		<div>
			<Navigation></Navigation>
			{children}
		</div>
	);
}